import jsPDF from 'jspdf';
import { ProjectReport } from '@oasis/asce7-calculator';

export function generatePdfReport(report: ProjectReport): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'letter',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 40;
  const contentWidth = pageWidth - margin * 2;
  let yPos = margin;
  let pageNumber = 1;

  const colors = {
    primary: [25, 118, 210] as [number, number, number],
    light: [240, 248, 255] as [number, number, number],
    dark: [33, 33, 33] as [number, number, number],
    border: [200, 200, 200] as [number, number, number],
  };

  const addFooter = () => {
    const footerY = pageHeight - 30;
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text(
      'Calculated per ASCE 7-22 Chapter 30 \u2014 Components & Cladding',
      margin,
      footerY
    );
    doc.text(
      'For buildings \u2264 60 ft mean roof height. Buildings > 60 ft require PE seal.',
      margin,
      footerY + 10
    );
    const rightText = 'Generated by windcalculations.com';
    const textWidth = doc.getTextWidth(rightText);
    doc.text(rightText, pageWidth - margin - textWidth, footerY);
    const dateText = `Date: ${new Date().toLocaleDateString()}`;
    const dateWidth = doc.getTextWidth(dateText);
    doc.text(dateText, pageWidth - margin - dateWidth, footerY + 10);
    doc.text(`Page ${pageNumber}`, pageWidth / 2, footerY + 20, { align: 'center' });
  };

  const checkPageBreak = (requiredSpace: number) => {
    if (yPos + requiredSpace > pageHeight - 60) {
      addFooter();
      doc.addPage();
      pageNumber++;
      yPos = margin;
      return true;
    }
    return false;
  };

  const drawTableRow = (items: { text: string; width: number }[], isBold = false, isHeader = false) => {
    let xPos = margin;
    if (isHeader) {
      doc.setFillColor(...colors.light);
      items.forEach((item) => {
        doc.rect(xPos, yPos - 9, item.width, 14, 'F');
        xPos += item.width;
      });
      xPos = margin;
    }
    doc.setFont('helvetica', isBold || isHeader ? 'bold' : 'normal');
    items.forEach((item) => {
      doc.text(item.text, xPos + 3, yPos, { maxWidth: item.width - 6 });
      xPos += item.width;
    });
    yPos += 14;
  };

  // Convenience references
  const p = report.project;
  const cf = report.commonFactors;

  // ============================================================
  // HEADER
  // ============================================================
  doc.setFontSize(20);
  doc.setTextColor(...colors.dark);
  doc.setFont('helvetica', 'bold');
  doc.text('WIND LOAD CALCULATION REPORT', margin, yPos);
  yPos += 24;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text('Per ASCE 7-22 \u2014 Components & Cladding (C&C)', margin, yPos);
  yPos += 20;

  // Separator line
  doc.setDrawColor(...colors.primary);
  doc.setLineWidth(2);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 20;

  // ============================================================
  // PROJECT INFO
  // ============================================================
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...colors.dark);
  doc.text('Project Information', margin, yPos);
  yPos += 16;

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const projectLines = [
    `Project: ${p.projectName}`,
    `Address: ${p.address}`,
    `Location: ${p.county} County, ${p.state}${p.isHVHZ ? ' (HVHZ)' : ''}`,
    `Date: ${new Date(report.calculatedAt).toLocaleDateString()}`,
  ];
  projectLines.forEach((line) => {
    doc.text(line, margin, yPos);
    yPos += 12;
  });
  yPos += 8;

  // ============================================================
  // BUILDING PARAMETERS TABLE
  // ============================================================
  checkPageBreak(130);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...colors.dark);
  doc.text('Building Parameters', margin, yPos);
  yPos += 16;

  doc.setFontSize(8);
  const halfWidth = contentWidth / 2;

  const buildingParams = [
    ['Design Wind Speed', `${p.ultimateWindSpeed} mph`],
    ['Exposure Category', `${p.exposureCategory}${p.exposureCategory === 'B' ? ' - Urban/Suburban' : p.exposureCategory === 'C' ? ' - Open Terrain' : ' - Shoreline'}`],
    ['Risk Category', `Category ${p.riskCategory ?? 2}`],
    ['Mean Roof Height', `${p.meanRoofHeight} ft`],
    ['Building Dimensions', `${p.buildingLength} ft x ${p.buildingWidth} ft`],
    ['Enclosure Type', p.enclosureType],
  ];

  // Header row
  drawTableRow([
    { text: 'Parameter', width: halfWidth },
    { text: 'Value', width: halfWidth },
  ], false, true);

  buildingParams.forEach((row, idx) => {
    if (idx % 2 === 0) {
      doc.setFillColor(248, 248, 248);
      doc.rect(margin, yPos - 9, contentWidth, 14, 'F');
    }
    doc.setTextColor(...colors.dark);
    drawTableRow([
      { text: row[0], width: halfWidth },
      { text: row[1], width: halfWidth },
    ]);
  });
  yPos += 8;

  // ============================================================
  // CALCULATION FACTORS TABLE
  // ============================================================
  checkPageBreak(140);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...colors.dark);
  doc.text('ASCE 7-22 Calculation Factors', margin, yPos);
  yPos += 16;

  doc.setFontSize(8);
  const factors = [
    ['Kd (Wind Directionality)', cf.kd.toFixed(2)],
    ['Kz (Velocity Pressure Exposure)', cf.kzRoof.toFixed(2)],
    ['Kzt (Topographic Factor)', cf.kzt.toFixed(2)],
    ['Ke (Ground Elevation Factor)', cf.ke.toFixed(2)],
    ['qh (Velocity Pressure at Roof)', `${cf.qh.toFixed(1)} psf`],
    ['GCpi (Internal Pressure Coeff.)', `+/-${cf.gcpiPositive.toFixed(2)}`],
    ['Zone End Width (a)', `${cf.zoneEndWidth.toFixed(1)} ft`],
  ];

  drawTableRow([
    { text: 'Factor', width: halfWidth },
    { text: 'Value', width: halfWidth },
  ], false, true);

  factors.forEach((row, idx) => {
    if (idx % 2 === 0) {
      doc.setFillColor(248, 248, 248);
      doc.rect(margin, yPos - 9, contentWidth, 14, 'F');
    }
    doc.setTextColor(...colors.dark);
    drawTableRow([
      { text: row[0], width: halfWidth },
      { text: row[1], width: halfWidth },
    ]);
  });
  yPos += 8;

  // ============================================================
  // OPENING SCHEDULE TABLE
  // ============================================================
  checkPageBreak(60);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...colors.dark);
  doc.text('Opening Schedule \u2014 C&C Design Pressures', margin, yPos);
  yPos += 16;

  doc.setFontSize(7);
  const colW = [35, 50, 55, 40, 30, 50, 50, 55, 55];
  const headers = ['Mark', 'Type', 'Size', 'Area(sf)', 'Zone', '+DP(psf)', '-DP(psf)', 'FL#', 'NOA#'];

  drawTableRow(headers.map((h, i) => ({ text: h, width: colW[i] })), false, true);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);

  report.openingResults.forEach((r, idx) => {
    checkPageBreak(14);
    if (idx % 2 === 0) {
      doc.setFillColor(248, 248, 248);
      let x = margin;
      colW.forEach((w) => { doc.rect(x, yPos - 9, w, 14, 'F'); x += w; });
    }
    doc.setTextColor(...colors.dark);

    const o = r.opening;
    const rowData = [
      o.markId,
      o.type,
      `${o.widthInches}"x${o.heightInches}"`,
      r.effectiveWindArea.toFixed(1),
      `Zone ${o.zone}`,
      `+${r.designPressurePositive.toFixed(1)}`,
      `-${r.designPressureNegative.toFixed(1)}`,
      o.flApproval || '-',
      o.noaNumber || '-',
    ];

    drawTableRow(rowData.map((text, i) => ({ text, width: colW[i] })));
  });
  yPos += 8;

  // ============================================================
  // ROOF C&C PRESSURES (if applicable)
  // ============================================================
  if (report.roofResults) {
    checkPageBreak(100);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...colors.dark);
    doc.text('Roof C&C Pressures', margin, yPos);
    yPos += 4;

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    if (p.roof) {
      doc.text(`Roof Type: ${p.roof.roofType}  |  Effective Area: ${p.roof.effectiveArea} sq ft`, margin, yPos);
    }
    yPos += 14;

    const roofColW = [120, 120, 120];
    doc.setFontSize(8);
    drawTableRow([
      { text: 'Zone', width: roofColW[0] },
      { text: '+DP (psf)', width: roofColW[1] },
      { text: '-DP (psf)', width: roofColW[2] },
    ], false, true);

    const zones = [
      { label: 'Zone 1 (Interior)', data: report.roofResults.zone1 },
      { label: 'Zone 2 (Eave/Ridge)', data: report.roofResults.zone2 },
      { label: 'Zone 3 (Corner)', data: report.roofResults.zone3 },
    ];

    zones.forEach((z, idx) => {
      if (idx % 2 === 0) {
        doc.setFillColor(248, 248, 248);
        let x = margin;
        roofColW.forEach((w) => { doc.rect(x, yPos - 9, w, 14, 'F'); x += w; });
      }
      doc.setTextColor(...colors.dark);
      drawTableRow([
        { text: z.label, width: roofColW[0] },
        { text: `+${z.data.positive.toFixed(1)}`, width: roofColW[1] },
        { text: `-${z.data.negative.toFixed(1)}`, width: roofColW[2] },
      ]);
    });
    yPos += 8;
  }

  // ============================================================
  // WARNINGS
  // ============================================================
  if (report.warnings && report.warnings.length > 0) {
    checkPageBreak(60);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(180, 130, 0);
    doc.text('Warnings & Notes', margin, yPos);
    yPos += 14;

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...colors.dark);

    report.warnings.forEach((warning) => {
      const lines = doc.splitTextToSize(`\u2022 ${warning}`, contentWidth);
      lines.forEach((line: string) => {
        checkPageBreak(12);
        doc.text(line, margin, yPos);
        yPos += 11;
      });
    });
    yPos += 6;
  }

  // ============================================================
  // COMPLIANCE STATEMENT
  // ============================================================
  checkPageBreak(60);
  doc.setDrawColor(...colors.border);
  doc.setLineWidth(0.5);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 14;

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(80, 80, 80);
  const complianceLines = [
    'Design pressures calculated per ASCE 7-22 (Components & Cladding methodology), Chapter 30.',
    'Applicable to enclosed and partially enclosed low-rise buildings with h \u2264 60 ft.',
    'For buildings over 60 ft mean roof height, calculations must be sealed by a licensed PE or Architect.',
    'Wind speed, exposure category, and topographic factors shall be verified by the designer of record.',
  ];
  complianceLines.forEach((line) => {
    doc.text(line, margin, yPos);
    yPos += 11;
  });

  // Add footer to final page
  addFooter();

  // Save
  const safeName = p.projectName.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 40);
  const dateStr = new Date().toISOString().split('T')[0];
  doc.save(`Wind_Load_Report_${safeName}_${dateStr}.pdf`);
}
