/**
 * PDF Generator for Homeowner Wind Certification Letter
 *
 * Generates a professional PDF certification letter using jsPDF library.
 * Used for submitting to building departments as part of permit applications.
 */

import jsPDF, { jsPDF as JSPDF } from 'jspdf';
import type {
  CalculatorOutput,
  ProductComparison,
  ProductRating,
} from '@oasis/asce7-calculator';

export interface LetterData {
  homeownerName: string;
  homeownerEmail: string;
  homeownerPhone: string;
  projectAddress: string;
  permitNumber?: string;
  county: string;
  calculatorOutput: CalculatorOutput;
  product: ProductRating;
  comparisonResult: ProductComparison;
}

/**
 * Generate a professional PDF certification letter
 *
 * @param data - Letter data including homeowner info, calculator output, product info
 * @returns Promise<Uint8Array> - PDF file as byte array
 */
export async function generateCertificationPDF(data: LetterData): Promise<Uint8Array> {
  // Create PDF document (8.5 x 11 inches, points)
  const doc = new JSPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'letter',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 50;
  const contentWidth = pageWidth - 2 * margin;

  let yPosition = margin;

  // Set default font
  doc.setFont('Helvetica');

  // ===== HEADER =====
  doc.setFontSize(16);
  doc.setFont('Helvetica', 'bold');
  doc.text('Homeowner Wind Load Verification Letter', margin, yPosition);

  yPosition += 20;

  // Add generated by footer
  doc.setFontSize(9);
  doc.setFont('Helvetica', 'italic');
  doc.setTextColor(100, 100, 100);
  doc.text(
    'Generated by Oasis Engineering Wind Certification Platform',
    margin,
    yPosition
  );
  doc.setTextColor(0, 0, 0);

  yPosition += 15;

  // ===== LETTER HEADER INFO =====
  doc.setFontSize(10);
  doc.setFont('Helvetica', 'normal');

  const today = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  });

  const headerInfo = [
    `Date: ${today}`,
    `Project Address: ${data.projectAddress}`,
    `County: ${data.county}`,
  ];

  if (data.permitNumber) {
    headerInfo.push(`Permit Number: ${data.permitNumber}`);
  }

  headerInfo.forEach((line) => {
    doc.text(line, margin, yPosition);
    yPosition += 12;
  });

  yPosition += 10;

  // ===== GREETING =====
  doc.setFontSize(10);
  doc.setFont('Helvetica', 'normal');

  doc.text(
    'Dear Building Department Official:',
    margin,
    yPosition
  );

  yPosition += 15;

  // ===== OPENING PARAGRAPH =====
  const openingText =
    'I am submitting this letter as part of my permit application for a like-for-like replacement of an exterior door/window at the above address. As the homeowner, I have used publicly available engineering tools and product documentation to verify that the proposed product meets or exceeds the wind load requirements for my location, in accordance with the Florida Building Code (FBC) and ASCE 7-22.';

  const openingLines = doc.splitTextToSize(openingText, contentWidth);
  doc.text(openingLines, margin, yPosition);
  yPosition += openingLines.length * 12 + 15;

  // Check if we need a new page
  if (yPosition > pageHeight - 100) {
    doc.addPage();
    yPosition = margin;
  }

  // ===== WIND LOAD COMPARISON TABLE SECTION =====
  doc.setFontSize(11);
  doc.setFont('Helvetica', 'bold');
  doc.text('Summary of Wind Load Comparison', margin, yPosition);
  yPosition += 15;

  // Create comparison table
  const tableData: (string | number)[][] = [
    ['Item', 'Value / Description'],
    ['Wind Speed (Vult)', `${data.calculatorOutput.input.ultimateWindSpeed} mph`],
    ['Exposure Category', data.calculatorOutput.input.exposureCategory],
    ['Mean Roof Height', `${data.calculatorOutput.input.meanRoofHeight} ft`],
    ['Effective Wind Area', `${data.calculatorOutput.input.effectiveWindArea} ft²`],
    [
      'Calculated Pressures',
      `+${data.calculatorOutput.criticalPressure.positive.toFixed(1)} / −${Math.abs(
        data.calculatorOutput.criticalPressure.negative
      ).toFixed(1)} psf`,
    ],
    ['Product Name', data.product.name],
  ];

  if (data.product.approvalNumber) {
    tableData.push(['Florida Product Approval', data.product.approvalNumber]);
  }

  tableData.push([
    'Rated Pressures',
    `+${data.product.ratedPositive} / −${data.product.ratedNegative} psf`,
  ]);

  // Draw table
  yPosition = drawTable(doc, margin, yPosition, contentWidth, tableData);

  yPosition += 15;

  // ===== COMPARISON RESULT SECTION =====
  doc.setFontSize(11);
  doc.setFont('Helvetica', 'bold');
  const resultText = data.comparisonResult.overallPass ? 'PASS - Product Approved' : 'FAIL - Product Not Approved';
  const resultColor = data.comparisonResult.overallPass ? [0, 100, 0] : [200, 0, 0];
  doc.setTextColor(resultColor[0], resultColor[1], resultColor[2]);
  doc.text(resultText, margin, yPosition);
  doc.setTextColor(0, 0, 0);

  yPosition += 15;

  // ===== DETAILED PRESSURE COMPARISON =====
  doc.setFontSize(10);
  doc.setFont('Helvetica', 'normal');

  const pressureComparisonText = `Based on ASCE 7-22 Chapter 30 calculations, the critical design pressures are +${data.calculatorOutput.criticalPressure.positive.toFixed(
    1
  )} psf (positive/inward) and −${Math.abs(
    data.calculatorOutput.criticalPressure.negative
  ).toFixed(
    1
  )} psf (negative/suction). The product is rated to withstand +${data.product.ratedPositive} psf and −${data.product.ratedNegative} psf. The product ${
    data.comparisonResult.overallPass
      ? 'meets or exceeds'
      : 'does not meet'
  } all required pressures for this location.`;

  const pressureLines = doc.splitTextToSize(pressureComparisonText, contentWidth);
  doc.text(pressureLines, margin, yPosition);
  yPosition += pressureLines.length * 12 + 15;

  if (yPosition > pageHeight - 150) {
    doc.addPage();
    yPosition = margin;
  }

  // ===== ZONE-BY-ZONE BREAKDOWN =====
  doc.setFontSize(10);
  doc.setFont('Helvetica', 'bold');
  doc.text('Detailed Zone Analysis', margin, yPosition);
  yPosition += 12;

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(9);

  const zoneInfo = [
    {
      name: 'Zone 4 (Interior)',
      positive: data.calculatorOutput.zone4.positive,
      negative: data.calculatorOutput.zone4.negative,
      posPass: data.comparisonResult.zone4.positivePass,
      negPass: data.comparisonResult.zone4.negativePass,
    },
    {
      name: 'Zone 5 (Corners/Edges - Governing Case)',
      positive: data.calculatorOutput.zone5.positive,
      negative: data.calculatorOutput.zone5.negative,
      posPass: data.comparisonResult.zone5.positivePass,
      negPass: data.comparisonResult.zone5.negativePass,
    },
  ];

  zoneInfo.forEach((zone) => {
    const posStatus = zone.posPass ? '✓' : '✗';
    const negStatus = zone.negPass ? '✓' : '✗';

    doc.text(`${zone.name}:`, margin + 10, yPosition);
    yPosition += 10;
    doc.text(
      `  Positive: +${zone.positive.toFixed(1)} psf (Rated: +${data.product.ratedPositive} psf) ${posStatus}`,
      margin + 15,
      yPosition
    );
    yPosition += 10;
    doc.text(
      `  Negative: −${Math.abs(zone.negative).toFixed(1)} psf (Rated: −${data.product.ratedNegative} psf) ${negStatus}`,
      margin + 15,
      yPosition
    );
    yPosition += 15;
  });

  if (yPosition > pageHeight - 100) {
    doc.addPage();
    yPosition = margin;
  }

  // ===== HVHZ WARNING (if applicable) =====
  if (data.calculatorOutput.input.isHVHZ) {
    doc.setFontSize(10);
    doc.setFont('Helvetica', 'bold');
    doc.setTextColor(200, 100, 0);
    doc.text('⚠ HIGH-VELOCITY HURRICANE ZONE (HVHZ) NOTICE', margin, yPosition);
    doc.setTextColor(0, 0, 0);
    yPosition += 12;

    doc.setFont('Helvetica', 'normal');
    doc.setFontSize(9);

    const hvhzText =
      'This location is in a High-Velocity Hurricane Zone (HVHZ). ' +
      'In addition to Florida Product Approval, products in HVHZ areas may require Miami-Dade County Notice of Acceptance (NOA) or equivalent county approval. ' +
      'Verify with your local building department and confirm that the selected product has all required approvals for your specific county.';

    const hvhzLines = doc.splitTextToSize(hvhzText, contentWidth - 20);
    doc.text(hvhzLines, margin + 10, yPosition);
    yPosition += hvhzLines.length * 11 + 15;
  }

  if (yPosition > pageHeight - 100) {
    doc.addPage();
    yPosition = margin;
  }

  // ===== DISCLAIMER SECTION =====
  doc.setFontSize(9);
  doc.setFont('Helvetica', 'bold');
  doc.text('Disclaimer', margin, yPosition);
  yPosition += 10;

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(8);

  const disclaimerText =
    'This letter is provided for informational and educational purposes only. ' +
    'It is not a professional engineering letter and is not signed and sealed by a licensed engineer. ' +
    'The homeowner assumes full responsibility for the accuracy of submitted information and compliance with local building codes. ' +
    'This documentation may not be sufficient for all jurisdictions. ' +
    'Contact your local building department before submission to confirm acceptability of homeowner-prepared wind load verification for like-for-like replacements. ' +
    'In High-Velocity Hurricane Zones, additional approvals may be required. ' +
    'See the full legal disclaimer at https://github.com/oasiseng/diy-wind-certification-guide/blob/main/disclaimer.md';

  const disclaimerLines = doc.splitTextToSize(disclaimerText, contentWidth - 20);
  doc.text(disclaimerLines, margin + 10, yPosition);
  yPosition += disclaimerLines.length * 9 + 15;

  if (yPosition > pageHeight - 80) {
    doc.addPage();
    yPosition = margin;
  }

  // ===== ATTACHMENT CHECKLIST =====
  doc.setFontSize(9);
  doc.setFont('Helvetica', 'bold');
  doc.text('📎 Attachments Included:', margin, yPosition);
  yPosition += 10;

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(9);

  const attachments = [
    '☐ Wind pressure calculator output (screenshot or PDF)',
    '☐ Florida Product Approval PDF or approval documentation',
    '☐ Product specifications or cut sheet',
    '☐ This certification letter',
  ];

  attachments.forEach((item) => {
    doc.text(item, margin + 15, yPosition);
    yPosition += 12;
  });

  yPosition += 15;

  // ===== SIGNATURE SECTION =====
  doc.setFontSize(10);
  doc.setFont('Helvetica', 'normal');

  doc.text('Thank you for your consideration.', margin, yPosition);
  yPosition += 15;

  doc.text('Sincerely,', margin, yPosition);
  yPosition += 30;

  // Signature line
  doc.setDrawColor(0, 0, 0);
  doc.line(margin, yPosition, margin + 150, yPosition);
  yPosition += 5;

  doc.setFontSize(9);
  doc.setFont('Helvetica', 'bold');
  doc.text(data.homeownerName, margin, yPosition);
  yPosition += 10;

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(8);

  const contactInfo = [
    `Phone: ${data.homeownerPhone}`,
    `Email: ${data.homeownerEmail}`,
    'Property Owner of Record',
  ];

  contactInfo.forEach((line) => {
    doc.text(line, margin, yPosition);
    yPosition += 10;
  });

  // ===== FOOTER =====
  doc.setFontSize(7);
  doc.setFont('Helvetica', 'italic');
  doc.setTextColor(150, 150, 150);

  doc.text('Generated by Oasis Engineering Wind Certification Platform', margin, pageHeight - 20);
  doc.text(
    `Document ID: ${generateDocumentId(data.projectAddress)}`,
    margin,
    pageHeight - 12
  );
  doc.text(`Generated: ${today}`, margin, pageHeight - 5);

  // Return PDF as Uint8Array
  return doc.output('arraybuffer') as Uint8Array;
}

/**
 * Helper function to draw a table in the PDF
 */
function drawTable(
  doc: InstanceType<typeof JSPDF>,
  x: number,
  y: number,
  width: number,
  data: (string | number)[][]
): number {
  const rowHeight = 14;
  const colWidth = width / 2;
  let currentY = y;

  // Draw header row
  doc.setFillColor(220, 220, 220);
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(9);

  doc.rect(x, currentY, colWidth, rowHeight, 'F');
  doc.rect(x + colWidth, currentY, colWidth, rowHeight, 'F');
  doc.text(String(data[0][0]), x + 5, currentY + 10);
  doc.text(String(data[0][1]), x + colWidth + 5, currentY + 10);

  currentY += rowHeight;

  // Draw data rows
  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(8);

  for (let i = 1; i < data.length; i++) {
    // Alternate row colors
    if (i % 2 === 0) {
      doc.setFillColor(245, 245, 245);
      doc.rect(x, currentY, width, rowHeight, 'F');
    } else {
      doc.setFillColor(255, 255, 255);
      doc.rect(x, currentY, width, rowHeight, 'F');
    }

    // Draw borders
    doc.setDrawColor(200, 200, 200);
    doc.rect(x, currentY, colWidth, rowHeight);
    doc.rect(x + colWidth, currentY, colWidth, rowHeight);

    // Split long text if needed
    const cell1Text = doc.splitTextToSize(String(data[i][0]), colWidth - 10);
    const cell2Text = doc.splitTextToSize(String(data[i][1]), colWidth - 10);

    doc.text(cell1Text, x + 5, currentY + 5);
    doc.text(cell2Text, x + colWidth + 5, currentY + 5);

    currentY += rowHeight;
  }

  // Draw outer border
  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.5);
  doc.rect(x, y, width, currentY - y);

  return currentY;
}

/**
 * Generate a unique document ID based on address and timestamp
 */
function generateDocumentId(address: string): string {
  const timestamp = Date.now().toString(36).toUpperCase();
  const addressHash = address
    .substring(0, 10)
    .replace(/[^a-zA-Z0-9]/g, '')
    .toUpperCase();
  return `WIND-${addressHash}-${timestamp}`;
}
